name: Pull after push on main branch
on:
  push:
    branches:
      - main
jobs:
  pull:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull latest changes
        run: git pull

